Create new order
MrFurion/QuickSolution pull request #12
Opened 2024-03-11 10:12 UTC by MrFurion

add page with create new order and interface EntityServices

2024-03-11 16:35 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +        System.out.println("Action 1");
давай использовать логи
log.info(..) для информации
log.error(..) для ошибок

2024-03-11 16:35 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +        System.out.println("Action 1");
Вывод в консоль считается плохой практикой, т.к. пишется это все в консоль сервера где куча еще другого и никто это не читает

2024-03-11 16:35 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +        System.out.println("Action 1");
А с использованием логгера у тебя появляется возможность указать/изменить куда именно эти логи будут писаться - в консоль, в файл, куда-то еще

2024-03-11 16:35 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +        orders.setDel(delivery);
а зачем delivery ставить в двух полях объекта orders?

2024-03-11 16:35 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +        Orders orders = new Orders();
У тебя один order или их несколько (может их можно пачкой создавать и отправлять)?

2024-03-11 16:35 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/interfaces/EntityServices.java
> +public interface EntityServices<T> {
интересное решение
Но я думаю в дальнейшем, когда сервисные классы у тебя станут слишком разные и добавится побольше бизнес-логики, всякой валидации и т.п., то это придется переделать
К тому же уже есть JpaRepository - там все эти методы есть

2024-03-12 09:40 UTC, aleksandr-kostochko commented on src/main/java/by/trubetski/quick/solution/models/Delivery.java
> +    public Delivery() {
@NoArgsConstructor

2024-03-12 09:40 UTC, aleksandr-kostochko commented on src/main/java/by/trubetski/quick/solution/models/Delivery.java
> +    public Delivery(String startAddress, String finishAddress) {
@AllArgsConstructor

2024-03-15 09:46 UTC, ladyka requested changes

2024-03-15 09:46 UTC, ladyka commented on DDL.sql
> +
Ззачем нужна эта новая строка?

2024-03-15 09:46 UTC, ladyka commented on pom.xml
> +			<version>2.21.1</version>
Версии лучше вынести в отдельную переменную и объявить в блоке <properties>

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +        System.out.println("Action 1");
Если уже что-то логируешь, то сделай сообщение более информативным. Твоё сообщение не несёт никакой смысловой нагрузки.

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +        System.out.println("Action 2");
Аналогично и с этим сообщением.

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/models/Delivery.java
> +
Это технический долг. И нет отражение в sql, что данная колонка удалена. Лучше работу над этим столбцом сделать или сделать в отдельном пул реквесте.

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +    public OrderController(OrderServices orderServices, UserServices userServices) {
Лучше заменить на @RequareArgsConstructor. Т.к. ломбок имеется в проекте.

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/models/OrderForm.java
> +    public OrderForm(String startAddress, String finishAddress, String orderName) {
@AllArgsConstructor

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/models/OrderForm.java
> +    public OrderForm() {
@NoArgsConstructor

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +    public OrderServices(UserRepositories userRepositories, OrderRepositories orderRepositories, UserServices userServices, DeliveryRepositories deliveryRepositories) {
@RequareArgsConstructor

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +        return null;
Не стоит переопределять работающую реализацию на неработающую.

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +    public List<OrderForm> findAll() {
Не стоит переопределять работающую реализацию на неработающую.

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +        System.out.println("Action 3");
логирование

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +        System.out.println("Action 4");
логирование.

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +    public void update(OrderForm entity) {
Не стоит переопределять работающую реализацию на неработающую.

2024-03-15 09:46 UTC, ladyka commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +    public void delete(int id) {
Не стоит переопределять работающую реализацию на неработающую.

2024-03-15 09:46 UTC, ladyka commented on src/main/resources/templates/orders/pageOrder.html
> +</html>
В конце файла нужна новая строка.

2024-03-26 20:42 UTC, YuliyaDzemidovich approved these changes
Вмержи этот ПР, пожалуйста - он стал уже слишком большим для ревью. В дальнейшем будем делать маленькие ПРы - каждый на отдельную фичу/тех долг.
***
В дальнейшем создавай, пожалуйста, отдельные ветки с названием фичи/содержимого, например ветка feature/create-new-order. Затем открывай ПР на мерж этой ветки в develop (не мастер).
Таким образом, у тебя будет отдельный ПР на каждую фичу, багфикс или рефакторинг.
***
Содержимое ПРа и название ПРа должны совпадать - в твоем случае это "create new order", а ты еще начинаешь добавлять сюда всякое другое. Кроме того, хорошая практика не держать ПРы открытыми больше дня или пары дней.

Соображения насчет наименования веток можно почитать здесь:
https://phoenixnap.com/kb/git-branch-name-convention

Для справки:
Мерж из develop'а в master выполняется лидом для релиза - как правило, это выходит за рамки работы рядового разработчика. Задача разработчиков - держать ветку develop всегда в рабочем состоянии, чтобы при необходимости можно было сделать релиз (мерж в мастер) в любой момент.

2024-03-28 07:07 UTC, merged