Feature/validation order form
MrFurion/QuickSolution pull request #14
Opened 2024-03-28 22:54 UTC by MrFurion

2024-03-30 08:57 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
>                              BindingResult bindingResult, Model model,
Test comment

2024-03-30 16:26 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +    public OrderController(OrderServices orderServices) {
лучше использовать ReqiredArgsConstructor аннотацию

2024-03-30 16:27 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +            log.info(orderForm.toString());
тут лучше log.error

2024-03-30 16:30 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/models/OrderForm.java
> +    private String startHouseNumber;
попробуй создать отдельный класс - например Appartment - вынеси туда houseNumber, entranceNumber, flatNumber,lat, lng. А потом два раза добавь атрибут Appartment в OrderForm - startAppartment и finishAppartment

2024-03-30 16:31 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +    public boolean save(OrderForm entity);
лучше оставить void и кидать эексепшены в случае ошибок. Соответственно там где этот метод будешь вызывать - оборачивать в try-case

2024-03-30 16:32 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
> +                             UserServices userServices, DeliveryRepositories deliveryRepositories, ItemRepositories itemRepositories, ValidationServices validationServices) {
RequiredArgsConstructor

2024-03-30 17:07 UTC, YuliyaDzemidovich requested changes

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +       boolean save = orderServices.save(orderForm);
булевские переменные о результате обычно ставят в форме деепричастия или пассива - isSaved, saved

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +        }else {
нужен пробел перед else

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/models/OrderForm.java
> +    private String startHouseNumber;
согласна, иначе это дублирование кода получается

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/models/OrderForm.java
> +    private String finishFlatNumber;
А если у меня дом а не квартира? А если нет подъезда

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/models/OrderForm.java
> +    @Size(min = 1, max = 10, message = " House number should be between 1 and 10character")
between X and Y characters - там же много символов, а не один.

Вообще налицо дублирование информации о валидации полей в самом сообщении о валидации. Но пока непонятно как это исправить, чтобы осталось красивое форматирование для вывода пользователю

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/ValidationServices.java
> +public interface ValidationServices {
где javadoc?

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
>          /**
/** - это обозначение javadoc комментария в джаве - такие комментарии внутри методов не оставляются
Почитай, пожалуйста, про 3 вида комментов в джаве - и используй тут (если надо) один из двух других видов комментов. Хотя по моему мнению, тут коммент вообще не нужен - код достаточно читабелен и без коммента

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/ValidationServicesImpl.java
> +
лишняя строчка

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/ValidationServicesImpl.java
> +    public ValidationServicesImpl(@Qualifier(value = "defaultValidator") Validator validator) {
а зачем тут qualifier - у тебя больше одного валидатора?
Если нет, тогда qualifier можно убрать и это спрячется под @RequiredArgConstructor

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/ValidationServicesImpl.java
> +        log.info(validator.toString());
нужен ли тут тебе лог при каждой валидации? Или выводить лог только в случае ошибок валидации?
Могу ли я с фронта вставить тебе "простыню" текста в логи?
Будет ли в логи выводиться приватная информация, типа имен и адресов пользователей?
Это в общем, на подумать тебе)

2024-03-30 17:07 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +        }else {
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2024-04-02 11:21 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/models/Apartment.java
> +    public Apartment(String city, String street, String houseNumber, String entranceNumber, String flatNumber, Double lat, Double lng) {
Этот конструктор тоже можно заменить @AllArgsConstructor. Кроме того, когда появляются конструкторы с таким большим количеством параметров, становится сложно в коде создавать объекты. Попробуй ломбоковский @Builder применить и соответственно создавать объекты через билдер

2024-04-02 11:22 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/models/Item.java
>      @OneToOne
Сомнительная связь OneToOne между Order и Item. Это означает, что у тебя в заказе всегда только один элемент. Если этот так, то стоит посмотреть - может Item можно в виде полей перенести в Order?

2024-04-02 11:24 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/models/Delivery.java
>  @Table(name = "Delivery")
При совпадаении имени таблицы и имени класса нет необходимости писать @Table. Если же на проекте принято такое соглашение для увеличения понимания кода, то нужно во всех Entity классах писать @Table.

2024-04-02 11:25 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/models/OrderForm.java
>  public class OrderForm {
OrderForm и Appartment лучше вынести в отдельную папку. Это не классы модели - это dto объекты. И стоит к названию классов добавить Dto

2024-04-07 11:21 UTC, YuliyaDzemidovich approved these changes

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/dto/ApartmentDto.java
> +
пустая строка тут не нужна

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/RegisterController.java
> +        log.info(bindingResult.toString());
если пишешь лог, тогда там нужны и нормальные слова что присходит
Иначе будет у тебя вывод например RegisterController: null - и вот как понять что это и что произошло?

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/dto/OrderFormDto.java
> +    public OrderFormDto() {
тут тоже подходит ломбок - @NoArgsContructor

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/dto/OrderFormDto.java
> +    public OrderFormDto(String deliveryType, String orderType, ApartmentDto startApartment, ApartmentDto finishApartment) {
Если сделать поля final, то подойдет @RequiredArgsContructor
А если не делать final, но можно и @AllArgsContructor

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/models/Item.java
>      @OneToOne
@DzianisShaplyka1984 привет, пока что это ограничение по ТЗ - что один предмет в заказе может быть. Вообще в дальнейшнем будет связь один-ко-многим, но не сейчас - иначе у него база разрастется, а фронт не готов еще будет. Пока что бОльший упор на законченность и целостность проекта

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/ValidationServices.java
> + * which takes an object of type T as an argument and returns a BindingResult object.
вот тут ты описываешь как раз то, что должно быть в джавадоке над методом (над строкой 11).
А джавадок над классом должен описывать сам класс - например, Service for validations.

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
>          orders.setStatus("New");
вот это в дальнешнем нужно будет вынести в константы - можно отдельный класс Constants
Или - еще лучше - создать enum с возможными order status'ами.

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
> +        String startAddress = ("City name: " + entity.getStartApartment().getCity() +
может быть в объекте просто переопределить метод toString?
И кстати название переменной entity плохое - по-моему это orderFormDto

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
>       *The method will check for the absence of duplicate email and name in the database. Additionally,
кстати лайфхак - если написал джавадок в интерфейсе (RegistrationServices), то джавадок в impl классе не нужен - он наследуется автоматически

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/UserServicesImpl.java
>  public class UserServicesImpl implements UserServices{
пробел до {

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/UserServicesImpl.java
>  public class UserServicesImpl implements UserServices{
попробуй настроить идею на javacode convention стиль и чтобы она сама поправляла форматирование

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/resources/static/js/loginPage/pageOrder.js
>          // Замените URL на URL вашего сервера и обработчика данных
это нужный коммент?

2024-04-07 11:21 UTC, YuliyaDzemidovich commented on src/main/resources/static/js/loginPage/pageOrder.js
> +        // Проверяем, были ли введены пользователем значения, и если нет, то устанавливаем дефолтные
этот коммент лучше над строкой 160 или даже 161 - устанавливаем дефолтные значения

2024-04-07 19:24 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/impl/ValidationServicesImpl.java
> +    public ValidationServicesImpl(@Qualifier(value = "defaultValidator") Validator validator) {
Необходим сама идея требует. Да есть еще 1.

2024-04-07 19:28 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/impl/UserServicesImpl.java
>  public class UserServicesImpl implements UserServices{
Но оно автоматически вроде как редактирует. Да и я сам постоянно командой ctr+alt+l редактирую. Но я учту!

2024-04-07 19:29 UTC, MrFurion commented on src/main/resources/static/js/loginPage/pageOrder.js
>          // Замените URL на URL вашего сервера и обработчика данных
Для себя что бы помнить что я здесь делал так как слабо разбираюсь в js и  css

2024-04-08 09:04 UTC, merged