add admin page
MrFurion/QuickSolution pull request #20
Opened 2024-04-17 19:32 UTC by MrFurion

2024-04-19 08:01 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +    public String edit(@PathVariable("id") int id, Model model){
Лучше назвать метод понятнее. Например showEditOrderPage

2024-04-19 08:04 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/services/impl/UserServicesImpl.java
> +        return StreamSupport.stream(userRepositories.findAll().spliterator(), false)
лучше сделать метод, который из базы вёрнет всех пользоватлеей с ролью Courier

2024-04-19 15:02 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +    public String edit(@PathVariable("id") int id, Model model){
если название переменной совпадает с названием атрибута/path параметра, то в новых версиях спринга просто можно опустить сам атрибут:
`@PathVariable int id, ...`

2024-04-19 15:10 UTC, YuliyaDzemidovich requested changes

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/AdminController.java
> +        return null;
может быть коммент или выбросить not implemented исключение? функционал явно не дописан

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +    @PatchMapping("/{id}")
почему не PUT?

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +            redirectAttributes.addFlashAttribute("successMessage", "Order successfully update!");
"order successfully updated" - это сокращенная (в рамках проф жаргона) форма от пассивного времени в английском: order is updated -> order updated. Точно так же как "page is not found" пишут короче "page not found"

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +    Optional<Orders> orderById(int id);
в джава док обязательно включаются параметры и возвращаемый тип - для них тоже нужно описание что это

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
> +        orders.setStatus(OrderStatus.STATUS_NEW.getStatusName());
зачем STATUS_NEW ? Возможно можно короче - просто NEW:
`OrderStatus.NEW`

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
> +     * @param id
не хватает джавадока для параметров - что за параметры

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
> +     * @param id
Возможно этот джавадок лучше смотрелся бы на уровне интерфейса, а не impl класса - там же нет ничего специфического для имплементации, а параметры метода относятся к контракту (интерфейсу)

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/UserServicesImpl.java
>              return user.get().getOrders();
пробел после } нужен:
`} else {`

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/UserServicesImpl.java
>      public int  getUserId(){
лишний пробел после int

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/UserServicesImpl.java
>          return user.orElse(null);
А это вообще будет работать? У тебя метод возвращает примитив. А ты в этой строке пытаешься вернуть null
Можно юнит тест на этот метод написать?

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/UserServicesImpl.java
> +        return StreamSupport.stream(userRepositories.findAll().spliterator(), false)
+1, иначе вытягиваешь лишнюю инфу из базы и перегружаешь базу

2024-04-19 15:10 UTC, YuliyaDzemidovich commented on src/main/resources/migrations/V4__DDL.sql
> +ALTER TABLE users RENAME column type to role;
гитхаб просит новую пустую строчку в конце каждого документа

2024-04-22 07:50 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/config/PasswordEncoderExample.java
> +        System.out.println(passwordEncoder.encode("Courier"));
Для чего хардкод пароля?

2024-04-22 07:57 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/config/PasswordEncoderExample.java
Комментарий ко всему PR.

Как только сделал PR, все последующие изменения в нём должны касаться только комментариев.

Плохая практика после начала ревью ещё наваливать изменений не относящихся к замечаниям, потому что непонятно где уже проревьювано, а где новое. Плюс пред. комменты могут оказаться неактуальным, плюс чем больше изменений, тем сложнее ревьювать.  

Лучше сделать отдельный PR.

2024-04-22 07:58 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/controllers/AdminController.java
> +    public String findAllUser(Model model, @RequestParam(name = "status", required = false) String status,
если имя параметра совпадает с именем переменной, можно не указывать.

но зависит от принятых соглашений на проекте.

2024-04-22 08:03 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/repositories/OrderRepositories.java
> +    List<Orders> getOrdersByStatusAndDelivery_CourierId(String status, String courierId);
Может стоит через method_name сделать? запрос не выглядит как очень сложный.

2024-04-22 08:04 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/repositories/UserRepositories.java
> +    List<User> getUserByRoleCourier(@Param("role") String role);
опять же, Query сдесь выглядит лишним. SpringData и по имени метода точно так же отработает.

2024-04-22 08:08 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/repositories/OrderRepositories.java
> +    List<Orders> getOrdersByStatusAndDelivery_CourierId(String status, String courierId);
Глянул по схеме БД. У тебя courieId - это int. Поэтому вместо String надо int или Integer использовать.

2024-04-22 08:09 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +    List<Orders> findOrdersByStatus(String statusDelivery, String courierPresence);
сдесь и в последующих вызовах вместо courierPresence лучше courierId использовать

2024-04-22 08:49 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/config/PasswordEncoderExample.java
> +        System.out.println(passwordEncoder.encode("Courier"));
Что бы напрямую создавать в консоли тестовых юзеров с уже хешированным паролём.

2024-04-22 08:52 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/repositories/OrderRepositories.java
> +    List<Orders> getOrdersByStatusAndDelivery_CourierId(String status, String courierId);
я здесь ищу не конкретного курьера а информацию с привязанными к доставки курьеров. То есть где уже есть курьер для доставки и где нету.

2024-04-23 12:10 UTC, merged