Feature/admin page
MrFurion/QuickSolution pull request #21
Opened 2024-04-24 10:25 UTC by MrFurion

2024-04-25 05:49 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/config/PasswordEncoderExample.java
> +        System.out.println(passwordEncoder.encode("Courier"));
вынести пароль из кода

2024-04-25 05:52 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/repositories/OrderRepositories.java
> +    @Query("FROM Orders where status = :status and (delivery.courierId = :courierId)")
лишний Query - Spring Data и так по названию метода сделает тоже самое

2024-04-25 05:57 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +    void update(int id, String orderStatus, int courierId);
два метода апдейт не нужно.

2024-04-25 05:57 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
> +    public void update(int id, OrderFormDto orderFormDto) {
пустой метод не нужен

2024-04-25 05:59 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
> +        Orders order = optionalOrder.get();
обернуть в проверку, если заказ пустой

2024-04-28 13:24 UTC, YuliyaDzemidovich requested changes
форматирование огонь, молодец!

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +        } catch (ValidationException e) {
а что будет если при update order выскочит какой-нибудь другой эксепшн?
Если я например в коде метода update напишу throw new RuntimeException() и запущу приложение - что будет когда я попытаюсь обновить заказ? Мне на фронте будет выведено сообщение об ошибке вроде "не удалось обновить заказ XYZ) или фронт просто ляжет со стектрейсом на всю страницу? :)

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +            log.error(bindingResult.toString());
как выглядит вот этот лог об ошибке - там видно какой именно заказ (orderId) не удалось обновить?
Представь ситуацию, что у тебя этот метод дергается в продакшене 10 раз в минуту - как ты найдешь нужный лог?

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/exception/OrderNotFoundException.java
> +public class OrderNotFoundException extends GlobalException{
как-то обрабатываются эти исключения по особенному или просто стектрейс на всю страницу пользователю вываливается?
И почему ты GlobalException решил наследовать от RuntimeException, а не от checked exception?

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +     * Use and extract data from OrderFormDto. It also validates the received data.
"Use and extract data from OrderFormDto" здесь док не нужен, т.к. это детали реализации. Save order and validate data достаточно: как именно это происходит - это уже за рамками ответственности этого интерфейса.

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +     * @param orderFormDto
Нужно писать джавадок так же для параметров:
`@param id Order ID`

Услышь меня, пожалуйста, и поставь себе SonarLint плагин для идеи. И у тебя таким места автоматом начнут подсвечиваться:
![1](https://github.com/MrFurion/QuickSolution/assets/30510213/e27ad8e2-e62d-4d5a-96e0-6400b4b42976)

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/UserServices.java
>       * Get the user's registration number.
registration number?
Немного размытое описание. По сигнатуре похоже, что этот метод делает get ID of currently authenticated user

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/UserServices.java
> +     * Find all User with role courier.
если по феншую, то на role можно прицепить ссылку на твой enum с ролями:
`{@link Role}` - и оно станет кликабельно после импорта

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/UserServices.java
> +     * Find all User with role courier.
даже `{@link Role.ROLE_COURIER}` точнее будет

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
> +            log.error("order not found by id");
по какому ID на найден? Можно вывести сам ID - и в лог, и в исключение

2024-04-28 13:24 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/util/enums/OrderStatus.java
> +public enum OrderStatus {
если очень хочется, вот тут можно подробно описать джавадоком что какой статус значит и в какой последовательности они обычно следуют.
Открой исходники джавы - во какие длинные джавадоки можно писать при желании)
Главное, чтобы доки помогали понимать код, а не запутывали еще больше

2024-04-29 17:38 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/exception/OrderNotFoundException.java
> +public class OrderNotFoundException extends GlobalException{
Проверка происходит вовремя работы программы например валидация данных. Да любая ошибка закреплена сообщением  которое уходит на UI где и отображается.

2024-04-29 17:41 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +        } catch (ValidationException e) {
Пока не занимаюсь этим флоу необходимо доделать админ страницу и ее возможности. Комментарии принял в дальнейшем использую.    Да на фронте будит отображаться соответствующее сообщение.

2024-04-29 17:41 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/controllers/OrderController.java
> +            log.error(bindingResult.toString());
Пока не занимаюсь этим флоу необходимо доделать админ страницу и ее возможности. Комментарии принял в дальнейшем использую.

2024-04-29 17:46 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/impl/OrderServicesImpl.java
> +            log.error("order not found by id");
согласен сделал

2024-04-29 17:50 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +     * Use and extract data from OrderFormDto. It also validates the received data.
Описания что происходит я так понимаю ненужно негде ?

2024-04-29 18:18 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/UserServices.java
> +     * Find all User with role courier.
Добавил

2024-04-29 18:18 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/OrderServices.java
> +     * @param orderFormDto
Сделал

2024-04-29 18:36 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/UserServices.java
>       * Get the user's registration number.
+

2024-05-01 15:55 UTC, merged