Feature/create courier page
MrFurion/QuickSolution pull request #23
Opened 2024-05-01 20:11 UTC by MrFurion

2024-05-03 12:45 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
> +           if (role.equals("User")){
вынести строки в константы или enum

2024-05-03 12:46 UTC, DzianisShaplyka1984 commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
> +               user.setRole(Role.ROLE_USER.getRoleName());
стоит сделать switсh вместо if/else

2024-05-04 18:44 UTC, YuliyaDzemidovich requested changes

2024-05-04 18:44 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/AdminController.java
> +    @GetMapping("/pageCrateCourier")
create?

2024-05-04 18:44 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/AdminController.java
> +                                   @RequestParam("role") String role){
если название переменной совпадает с названием атрибута, то последнее указывать необязательно:
`@RequestParam String role`
скорее всего с modelAttribute так же

2024-05-04 18:44 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/AdminController.java
> +            log.error(bindingResult.toString());
здесь лучше написать откуда валится ошибка
`log.error("Cannot create courier role: {}", bindingResult.toString());`
Вообще надо потыкать твое приложение, посмотреть какие ошибки там вываливаются и как это выглядит для пользователя

2024-05-04 18:44 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/RegistrationServices.java
> +    void createCourier(User user, String role);
джавадок

2024-05-04 18:44 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
> +            throw new ValidationException("error of validation");
возможно, здесь нужна более подробное описание а почему именно не прошла валидация

2024-05-04 18:44 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
> +            throw new UsernameAlreadyExistsException("Username already exists");
на будущее - эта и 72-я строки это потенциальная уязвимость, т.к позволяет злоумышленнику брут форсом перебрать а какие юзеры и имейлы зареганы в системе
[подробнее про user enumeration можно почитать тут](https://www.rapid7.com/blog/post/2017/06/15/about-user-enumeration/)
Пока что можно просто исправить сообщение на "Username is not allowed" или что-то в более общем духе. Уязвимость это не уберет, но она станет менее очевидно - мало ли почему такой username не разрешен.

2024-05-04 18:47 UTC, YuliyaDzemidovich commented on src/main/java/by/trubetski/quick/solution/controllers/AdminController.java
> +    @GetMapping("/pageCrateCourier")
кстати, если передаешь чувствительные данные для создание курьера (или любого другого юзера), то GET тут крайне нежелательно использовать - только POST
[сравнительная табличка например вот здесь](https://www.w3schools.com/tags/ref_httpmethods.asp)
Ах да, еще кэширование, идемпотентность и вот это всё :)

2024-05-04 23:01 UTC, detalby commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
> +               user.setRole(Role.ROLE_USER.getRoleName());
вообще можно более элегантно это сделать.
 1. Почему Enum Role не используется в User, а используется стринга?
 2. Делается мапа ролей и достается роль по ключу. как вариант 
 ... Бесплатный совет :)

2024-05-05 11:33 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
> +               user.setRole(Role.ROLE_USER.getRoleName());
По ключу наверное будит лишний код я думаю и медленнее. Но я попробую спасибо.

2024-05-05 11:38 UTC, detalby commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
> +               user.setRole(Role.ROLE_USER.getRoleName());
Медленнее ?) У вас сейчас какая алгоритмическая  сложность ?

2024-05-05 11:58 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/controllers/AdminController.java
> +                                   @RequestParam("role") String role){
Я бы пока хотел оставить так, что бы самому видеть что откуда и куда идет. Поэтому пусть пока указано явно.

2024-05-05 12:04 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
> +            throw new UsernameAlreadyExistsException("Username already exists");
Тоже были сомнения. Нашел такое оформление и решил применить. Исправил!

2024-05-05 13:07 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/controllers/AdminController.java
> +    @GetMapping("/pageCrateCourier")
Это точка перехода на страницу здесь я пока нечего не передаю.

2024-05-05 13:25 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/RegistrationServices.java
> +    void createCourier(User user, String role);
Выполнено.

2024-05-05 13:50 UTC, MrFurion commented on src/main/java/by/trubetski/quick/solution/services/impl/RegistrationServicesImpl.java
> +            throw new ValidationException("error of validation");
У меня каждое поле возвращает причину по которой не проходит валидация. А здесь просто информация что валидация не прошла решил сделать так throw new ValidationException("Please try again");

2024-05-06 07:56 UTC, merged